# Generated by Django 4.2.20 on 2025-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_video_likes_count_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='reaction_type',
            field=models.CharField(choices=[('like', '👍'), ('dislike', '👎')], default='👍', max_length=7),
        ),
    ]
