# Generated by Django 4.2.20 on 2025-05-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_like_reaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
