# Generated by Django 4.2.20 on 2025-05-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='reels/', verbose_name='Reels file')),
                ('likes_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
