# Generated by Django 4.2.20 on 2025-05-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_videoview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoview',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='main.video'),
        ),
    ]
