# Generated by Django 4.2.20 on 2025-05-31 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_category_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
