# Generated by Django 4.2.20 on 2025-06-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_video_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('processed', 'Обработано')], default='pending', max_length=20),
        ),
    ]
